version: '3'
services:
  app1:
    image: app2
    build: ./app2
    ports:
    - "5000:5000"
    deploy:
      mode: replicated
      replicas: 14
  nginx:
    image: nginx
    build: ./nginx 
    ports:
    - "8090:80"
    depends_on:
      - app1

